// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SlimFinancial.Infrastructure.Data;

#nullable disable

namespace SlimFinancial.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20241111230546_InitialMigration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.10");

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("SlimFinancial.Domain.Models.Account", b =>
                {
                    b.Property<int>("AccountNumber")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(1100100100)
                        .HasAnnotation("Sqlite:Autoincrement", true);

                    b.Property<double>("Balance")
                        .HasColumnType("REAL");

                    b.Property<int>("PersonNumber")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("PersonNumber1")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("AccountNumber");

                    b.HasIndex("PersonNumber1");

                    b.ToTable("Accounts");
                });

            modelBuilder.Entity("SlimFinancial.Domain.Models.AccountDebitCard", b =>
                {
                    b.Property<int>("Pan")
                        .HasColumnType("INTEGER");

                    b.Property<int>("AccountNumber")
                        .HasColumnType("INTEGER");

                    b.HasKey("Pan", "AccountNumber");

                    b.HasIndex("AccountNumber");

                    b.ToTable("AccountDebitCard");
                });

            modelBuilder.Entity("SlimFinancial.Domain.Models.AccountTransaction", b =>
                {
                    b.Property<int>("AccountNumber")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TransactionId")
                        .HasColumnType("TEXT");

                    b.HasKey("AccountNumber", "TransactionId");

                    b.HasIndex("TransactionId");

                    b.ToTable("AccountTransactions");
                });

            modelBuilder.Entity("SlimFinancial.Domain.Models.DebitCard", b =>
                {
                    b.Property<int>("Pan")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(429448001)
                        .HasAnnotation("Sqlite:Autoincrement", true);

                    b.Property<DateOnly>("DateCreated")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PersonNumber")
                        .HasColumnType("INTEGER");

                    b.HasKey("Pan");

                    b.ToTable("DebitCards");
                });

            modelBuilder.Entity("SlimFinancial.Domain.Models.Person", b =>
                {
                    b.Property<int>("PersonNumber")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(1701000)
                        .HasAnnotation("Sqlite:Autoincrement", true);

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("DateOfBirth")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Fname")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Id")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("INTEGER")
                        .HasComputedColumnSql("PersonNumber", true);

                    b.Property<string>("Lname")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("TEXT");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("TEXT");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("PersonNumber");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("Persons", (string)null);
                });

            modelBuilder.Entity("SlimFinancial.Domain.Models.PersonAccount", b =>
                {
                    b.Property<int>("PersonNumber")
                        .HasColumnType("INTEGER");

                    b.Property<int>("AccountNumber")
                        .HasColumnType("INTEGER");

                    b.HasKey("PersonNumber", "AccountNumber");

                    b.HasIndex("AccountNumber");

                    b.ToTable("JointAccounts", (string)null);
                });

            modelBuilder.Entity("SlimFinancial.Domain.Models.PersonDebitCard", b =>
                {
                    b.Property<int>("Pan")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PersonNumber")
                        .HasColumnType("INTEGER");

                    b.HasKey("Pan", "PersonNumber");

                    b.HasIndex("PersonNumber");

                    b.ToTable("PersonDebitCards");
                });

            modelBuilder.Entity("SlimFinancial.Domain.Models.Transaction", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int>("AccountNumber")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Amount")
                        .HasColumnType("REAL");

                    b.Property<double>("Balance")
                        .HasColumnType("REAL");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TransactionType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Transactions");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.HasOne("SlimFinancial.Domain.Models.Person", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.HasOne("SlimFinancial.Domain.Models.Person", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.HasOne("SlimFinancial.Domain.Models.Person", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SlimFinancial.Domain.Models.Account", b =>
                {
                    b.HasOne("SlimFinancial.Domain.Models.Person", "Person")
                        .WithMany("Accounts")
                        .HasForeignKey("PersonNumber1");

                    b.Navigation("Person");
                });

            modelBuilder.Entity("SlimFinancial.Domain.Models.AccountDebitCard", b =>
                {
                    b.HasOne("SlimFinancial.Domain.Models.DebitCard", "DebitCard")
                        .WithMany("LinkedAccounts")
                        .HasForeignKey("AccountNumber")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SlimFinancial.Domain.Models.Account", "Account")
                        .WithMany("DebitCards")
                        .HasForeignKey("Pan")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");

                    b.Navigation("DebitCard");
                });

            modelBuilder.Entity("SlimFinancial.Domain.Models.AccountTransaction", b =>
                {
                    b.HasOne("SlimFinancial.Domain.Models.Account", "Account")
                        .WithMany("Transactions")
                        .HasForeignKey("AccountNumber")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SlimFinancial.Domain.Models.Transaction", "Transaction")
                        .WithMany("Accounts")
                        .HasForeignKey("TransactionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");

                    b.Navigation("Transaction");
                });

            modelBuilder.Entity("SlimFinancial.Domain.Models.PersonAccount", b =>
                {
                    b.HasOne("SlimFinancial.Domain.Models.Account", "Account")
                        .WithMany("JointOwners")
                        .HasForeignKey("AccountNumber")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SlimFinancial.Domain.Models.Person", "Person")
                        .WithMany("JointAccounts")
                        .HasForeignKey("PersonNumber")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");

                    b.Navigation("Person");
                });

            modelBuilder.Entity("SlimFinancial.Domain.Models.PersonDebitCard", b =>
                {
                    b.HasOne("SlimFinancial.Domain.Models.DebitCard", "DebitCard")
                        .WithMany("Persons")
                        .HasForeignKey("Pan")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SlimFinancial.Domain.Models.Person", "Person")
                        .WithMany("DebitCards")
                        .HasForeignKey("PersonNumber")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DebitCard");

                    b.Navigation("Person");
                });

            modelBuilder.Entity("SlimFinancial.Domain.Models.Account", b =>
                {
                    b.Navigation("DebitCards");

                    b.Navigation("JointOwners");

                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("SlimFinancial.Domain.Models.DebitCard", b =>
                {
                    b.Navigation("LinkedAccounts");

                    b.Navigation("Persons");
                });

            modelBuilder.Entity("SlimFinancial.Domain.Models.Person", b =>
                {
                    b.Navigation("Accounts");

                    b.Navigation("DebitCards");

                    b.Navigation("JointAccounts");
                });

            modelBuilder.Entity("SlimFinancial.Domain.Models.Transaction", b =>
                {
                    b.Navigation("Accounts");
                });
#pragma warning restore 612, 618
        }
    }
}
